version: '3.8'
services:
  validation-service:
    build:
      context: .
      dockerfile: Dockerfile.service
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
      - PORT=8080
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=secretsuser
      - DB_PASSWORD=secretspass
      - DB_NAME=secretsdb
    depends_on:
      - postgres
    networks:
      - secret-validator-network

  github-app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "3000:8080"
    volumes:
      - ./config/config.json:/app/config/config.json
      - ./keys:/app/keys
    environment:
      - APP_ENV=development
      - LOG_LEVEL=debug
      - VALIDATION_SERVICE_URL=http://validation-service:8080
      - GITHUB_APP_ID=${GITHUB_APP_ID:-12345}
      - GITHUB_INSTALLATION_ID=${GITHUB_INSTALLATION_ID:-67890}
      - GITHUB_WEBHOOK_SECRET=${GITHUB_WEBHOOK_SECRET:-development_webhook_secret_123}
      - TEST_MODE=${TEST_MODE:-false}  # Add this for test mode toggle
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=secretsuser
      - DB_PASSWORD=secretspass
      - DB_NAME=secretsdb
    depends_on:
      - validation-service
      - postgres
    networks:
      - secret-validator-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=secretsuser
      - POSTGRES_PASSWORD=secretspass
      - POSTGRES_DB=secretsdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - secret-validator-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - postgres
    networks:
      - secret-validator-network

volumes:
  postgres_data:
  grafana_data:

networks:
  secret-validator-network:
    driver: bridge