# Development environment configuration overrides

# Set image tag for development
images:
  githubApp:
    tag: dev
    pullPolicy: Always  # Always pull latest dev images
  validationService:
    tag: dev
    pullPolicy: Always

# Development settings for GitHub App
githubApp:
  config:
    logLevel: debug
    testMode: true  # Enable test mode for easier testing
    fullFileAnalysis: true  # Enable full file analysis for better debugging
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

# Development settings for Validation Service
validationService:
  config:
    ginMode: debug  # Set Gin to debug mode for more verbose logs
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

# Use local database for development
database:
  host: "postgres-service"  # Local service in the same namespace
  port: 5432
  name: "secretsdb"
  username: "devuser"
  password: "devpassword"

# Optional ingress for local development
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: secrets-detector.dev.local
      paths:
        - path: /webhook
          pathType: Prefix