apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "secrets-detector.fullname" . }}-config
  labels:
    {{- include "secrets-detector.labels" . | nindent 4 }}
data:
  config.json: |-
    {
      "patterns": {
        "aws_key": "AKIA[0-9A-Z]{16}",
        "aws_secret": "(?i)[0-9a-z]{40}",
        "private_key": "-----BEGIN\\s*(?:RSA|DSA|EC|OPENSSH|PRIVATE)\\s*KEY-----",
        "certificate": "-----BEGIN\\s*CERTIFICATE-----",
        "github_token": "gh[pos]_[0-9a-zA-Z]{36}",
        "jwt_token": "eyJ[A-Za-z0-9-_=]+\\.[A-Za-z0-9-_=]+\\.?[A-Za-z0-9-_.+/=]*",
        "ssh_key": "ssh-rsa\\s+[A-Za-z0-9+/]+[=]{0,3}(\\s+[^@]+@[^@]+)?",
        "google_api": "AIza[0-9A-Za-z\\-_]{35}",
        "stripe_key": "(?i)(sk|pk)_(test|live)_[0-9a-z]{24,99}",
        "slack_token": "xox[baprs]-([0-9a-zA-Z]{10,48})?",
        "slack_webhook": "https://hooks\\.slack\\.com/services/T[a-zA-Z0-9_]{8}/B[a-zA-Z0-9_]{8}/[a-zA-Z0-9_]{24}"
      },
      "api": {
        "validate_endpoint": "http://localhost:8080/validate",
        "token": "your-auth-token-here",
        "timeout_seconds": 30,
        "retry_attempts": 3
      },
      "logging": {
        "level": "INFO",
        "file": "/var/log/secret-validator.log",
        "max_size_mb": 100,
        "max_backups": 3,
        "max_age_days": 28,
        "compress": true
      },
      "rules": {
        "block_on_validation_failure": true,
        "notify_admins": true,
        "allowed_branches": [
          "develop",
          "feature/*",
          "bugfix/*",
          "release/*"
        ],
        "excluded_files": [
          "*.test.key",
          "test/fixtures/*",
          "**/*.md",
          "docs/*"
        ],
        "excluded_paths": [
          ".git/*",
          "node_modules/*",
          "vendor/*"
        ],
        "size_limits": {
          "max_file_size_mb": 10,
          "max_diff_size_mb": 50
        }
      },
      "validation": {
        "certificate": {
          "check_expiry": true,
          "min_days_valid": 30,
          "allowed_issuers": [
            "Let's Encrypt",
            "Company Internal CA"
          ]
        },
        "private_key": {
          "min_key_size": 2048,
          "allowed_types": ["RSA", "EC"]
        },
        "api_keys": {
          "validate_format": true,
          "check_revocation": true
        }
      }
    }

  # Grafana provisioning for datasources
  datasources.yaml: |-
    apiVersion: 1
    
    datasources:
      - name: PostgreSQL
        type: postgres
        url: {{ include "secrets-detector.postgresHost" . }}:{{ include "secrets-detector.postgresPort" . }}
        user: {{ .Values.postgres.credentials.username }}
        secureJsonData:
          password: {{ .Values.postgres.credentials.password }}
        jsonData:
          database: {{ .Values.postgres.credentials.database }}
          sslmode: disable
          maxOpenConns: 100
          maxIdleConns: 100
          maxIdleConnsAuto: true
          connMaxLifetime: 14400
          postgresVersion: 1500
          timescaledb: false
        isDefault: true

  # Grafana dashboard provision config
  dashboards.yaml: |-
    apiVersion: 1
    
    providers:
      - name: Default
        folder: ''
        type: file
        disableDeletion: true
        editable: true
        allowUiUpdates: true
        options:
          path: /var/lib/grafana/dashboards
          foldersFromFilesStructure: true

  # Database init script
  init.sql: |-
    CREATE TABLE IF NOT EXISTS repositories (
        id SERIAL PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        owner VARCHAR(255) NOT NULL,
        is_enterprise BOOLEAN DEFAULT false,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
        UNIQUE(owner, name)
    );
    
    CREATE TABLE IF NOT EXISTS secret_detections (
        id SERIAL PRIMARY KEY,
        repository_id INTEGER REFERENCES repositories(id),
        commit_hash VARCHAR(40) NOT NULL,
        secret_type VARCHAR(50) NOT NULL,
        secret_location TEXT NOT NULL,
        line_number INTEGER,
        is_blocked BOOLEAN DEFAULT false,
        detected_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
        validation_status VARCHAR(20) NOT NULL,
        branch_name VARCHAR(255),
        author VARCHAR(255),
        commit_timestamp TIMESTAMP WITH TIME ZONE
    );
    
    CREATE TABLE IF NOT EXISTS validation_history (
        id SERIAL PRIMARY KEY,
        detection_id INTEGER REFERENCES secret_detections(id),
        validation_result BOOLEAN NOT NULL,
        validation_message TEXT,
        validated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );
    
    CREATE INDEX idx_detections_repo ON secret_detections(repository_id);
    CREATE INDEX idx_detections_date ON secret_detections(detected_at);
    CREATE INDEX idx_detections_type ON secret_detections(secret_type);
    CREATE INDEX idx_detections_status ON secret_detections(validation_status);
    
    -- Create views for executive dashboards
    CREATE VIEW secret_detection_metrics AS
    SELECT 
        DATE_TRUNC('day', detected_at) as detection_date,
        r.owner,
        r.name as repository_name,
        secret_type,
        validation_status,
        COUNT(*) as detection_count,
        SUM(CASE WHEN is_blocked THEN 1 ELSE 0 END) as blocked_count
    FROM secret_detections sd
    JOIN repositories r ON r.id = sd.repository_id
    GROUP BY 
        DATE_TRUNC('day', detected_at),
        r.owner,
        r.name,
        secret_type,
        validation_status;
    
    CREATE VIEW repository_risk_metrics AS
    SELECT 
        r.owner,
        r.name as repository_name,
        COUNT(*) as total_detections,
        COUNT(DISTINCT secret_type) as unique_secret_types,
        MAX(detected_at) as last_detection,
        SUM(CASE WHEN is_blocked THEN 1 ELSE 0 END) as total_blocked
    FROM secret_detections sd
    JOIN repositories r ON r.id = sd.repository_id
    GROUP BY r.owner, r.name;

  # Executive dashboard JSON for Grafana
  executive-dashboard.json: |-
    {"annotations":{"list":[]},"editable":true,"fiscalYearStartMonth":0,"graphTooltip":0,"id":1,"links":[],"liveNow":false,"panels":[{"datasource":{"type":"postgres","uid":"PostgreSQL"},"fieldConfig":{"defaults":{"color":{"mode":"palette-classic"},"mappings":[],"thresholds":{"mode":"absolute","steps":[{"color":"green","value":null},{"color":"yellow","value":5},{"color":"red","value":10}]}},"overrides":[]},"gridPos":{"h":8,"w":6,"x":0,"y":0},"id":1,"options":{"colorMode":"value","graphMode":"area","justifyMode":"auto","orientation":"auto","reduceOptions":{"calcs":["lastNotNull"],"fields":"","values":false},"textMode":"auto"},"title":"Total Secrets (30 Days)","type":"stat","targets":[{"datasource":{"type":"postgres","uid":"PostgreSQL"},"sql":"SELECT COUNT(*) as value FROM secret_detections WHERE detected_at >= NOW() - INTERVAL '30 days'","format":"table"}]},{"datasource":{"type":"postgres","uid":"PostgreSQL"},"fieldConfig":{"defaults":{"color":{"mode":"palette-classic"},"mappings":[],"thresholds":{"mode":"absolute","steps":[{"color":"green","value":null}]}},"overrides":[]},"gridPos":{"h":8,"w":6,"x":6,"y":0},"id":2,"options":{"colorMode":"value","graphMode":"area","justifyMode":"auto","orientation":"auto","reduceOptions":{"calcs":["lastNotNull"],"fields":"","values":false},"textMode":"auto"},"title":"Unique Repositories Affected","type":"stat","targets":[{"datasource":{"type":"postgres","uid":"PostgreSQL"},"sql":"SELECT COUNT(DISTINCT repository_id) as value FROM secret_detections WHERE detected_at >= NOW() - INTERVAL '30 days'","format":"table"}]},{"datasource":{"type":"postgres","uid":"PostgreSQL"},"fieldConfig":{"defaults":{"color":{"mode":"continuous-GrYlRd"},"custom":{"axisCenteredZero":false,"axisColorMode":"text","axisLabel":"","axisPlacement":"auto","barAlignment":0,"drawStyle":"line","fillOpacity":20,"gradientMode":"none","hideFrom":{"legend":false,"tooltip":false,"viz":false},"lineInterpolation":"smooth","lineWidth":2,"pointSize":5,"scaleDistribution":{"type":"linear"},"showPoints":"never","spanNulls":true,"stacking":{"group":"A","mode":"none"},"thresholdsStyle":{"mode":"off"}},"mappings":[],"thresholds":{"mode":"absolute","steps":[{"color":"green","value":null}]},"unit":"short"},"overrides":[]},"gridPos":{"h":8,"w":12,"x":12,"y":0},"id":3,"options":{"legend":{"calcs":[],"displayMode":"list","placement":"bottom","showLegend":true},"tooltip":{"mode":"single","sort":"none"}},"targets":[{"datasource":{"type":"postgres","uid":"PostgreSQL"},"sql":"SELECT date_trunc('day', detected_at) as time, COUNT(*) as value FROM secret_detections WHERE detected_at >= NOW() - INTERVAL '30 days' GROUP BY 1 ORDER BY 1","format":"time_series"}],"title":"Daily Detection Trend","type":"timeseries"},{"datasource":{"type":"postgres","uid":"PostgreSQL"},"fieldConfig":{"defaults":{"color":{"mode":"palette-classic"},"custom":{"hideFrom":{"legend":false,"tooltip":false,"viz":false}},"mappings":[]},"overrides":[]},"gridPos":{"h":8,"w":12,"x":0,"y":8},"id":4,"options":{"displayLabels":["value","percentage"],"legend":{"displayMode":"list","placement":"right","showLegend":true},"pieType":"pie","reduceOptions":{"calcs":["lastNotNull"],"fields":"","values":true},"tooltip":{"mode":"single","sort":"none"}},"title":"Secret Types Distribution","type":"piechart","targets":[{"datasource":{"type":"postgres","uid":"PostgreSQL"},"sql":"SELECT secret_type, COUNT(*) as value FROM secret_detections WHERE detected_at >= NOW() - INTERVAL '30 days' GROUP BY secret_type ORDER BY value DESC","format":"table"}]},{"datasource":{"type":"postgres","uid":"PostgreSQL"},"fieldConfig":{"defaults":{"color":{"mode":"thresholds"},"custom":{"align":"auto","cellOptions":{"type":"auto"},"inspect":false},"mappings":[],"thresholds":{"mode":"absolute","steps":[{"color":"green","value":null}]}},"overrides":[]},"gridPos":{"h":8,"w":12,"x":12,"y":8},"id":5,"options":{"footer":{"countRows":false,"fields":"","reducer":["sum"],"show":false},"showHeader":true},"title":"Top Repositories by Risk","type":"table","targets":[{"datasource":{"type":"postgres","uid":"PostgreSQL"},"sql":"SELECT r.owner, r.name as repository, COUNT(*) as total_detections, COUNT(DISTINCT secret_type) as unique_secret_types, MAX(detected_at) as last_detection FROM secret_detections sd JOIN repositories r ON r.id = sd.repository_id WHERE detected_at >= NOW() - INTERVAL '30 days' GROUP BY r.owner, r.name ORDER BY total_detections DESC LIMIT 10","format":"table"}]}],"refresh":"5m","schemaVersion":38,"style":"dark","tags":["secrets","security"],"templating":{"list":[]},"time":{"from":"now-30d","to":"now"},"timepicker":{},"timezone":"","title":"Secrets Detection Executive Dashboard","uid":"secrets-exec-dash","version":1,"weekStart":""}

  # Repository metrics dashboard JSON for Grafana
  repository-metrics.json: |-
    {"annotations":{"list":[]},"editable":true,"fiscalYearStartMonth":0,"graphTooltip":0,"id":2,"links":[],"liveNow":false,"panels":[{"datasource":{"type":"postgres","uid":"PostgreSQL"},"fieldConfig":{"defaults":{"custom":{"align":"auto","cellOptions":{"type":"auto"},"filterable":true,"inspect":false},"mappings":[],"thresholds":{"mode":"absolute","steps":[{"color":"green","value":null},{"color":"yellow","value":5},{"color":"red","value":10}]}},"overrides":[]},"gridPos":{"h":8,"w":24,"x":0,"y":0},"id":1,"options":{"footer":{"countRows":false,"fields":"","reducer":["sum"],"show":false},"showHeader":true,"sortBy":[{"desc":true,"displayName":"Total Detections"}]},"targets":[{"datasource":{"type":"postgres","uid":"PostgreSQL"},"sql":"SELECT r.owner, r.name as repository, COUNT(*) as total_detections, COUNT(DISTINCT secret_type) as unique_secret_types, COUNT(CASE WHEN is_blocked THEN 1 END) as blocked_pushes, MAX(detected_at) as last_detection, COUNT(CASE WHEN detected_at >= NOW() - INTERVAL '7 days' THEN 1 END) as detections_last_7d FROM secret_detections sd JOIN repositories r ON r.id = sd.repository_id GROUP BY r.owner, r.name ORDER BY total_detections DESC","format":"table"}],"title":"Repository Risk Overview","type":"table","transformations":[]},{"datasource":{"type":"postgres","uid":"PostgreSQL"},"fieldConfig":{"defaults":{"color":{"mode":"continuous-GrYlRd"},"custom":{"axisCenteredZero":false,"axisColorMode":"text","axisLabel":"","axisPlacement":"auto","barAlignment":0,"drawStyle":"bars","fillOpacity":80,"gradientMode":"none","hideFrom":{"legend":false,"tooltip":false,"viz":false},"lineInterpolation":"linear","lineWidth":1,"pointSize":5,"scaleDistribution":{"type":"linear"},"showPoints":"never","spanNulls":true,"stacking":{"group":"A","mode":"none"},"thresholdsStyle":{"mode":"off"}},"mappings":[],"thresholds":{"mode":"absolute","steps":[{"color":"green","value":null}]}},"overrides":[]},"gridPos":{"h":8,"w":12,"x":0,"y":8},"id":2,"options":{"legend":{"calcs":[],"displayMode":"list","placement":"bottom","showLegend":true},"tooltip":{"mode":"single","sort":"none"}},"targets":[{"datasource":{"type":"postgres","uid":"PostgreSQL"},"sql":"SELECT date_trunc('day', detected_at) as time, COUNT(*) as value, r.name as metric FROM secret_detections sd JOIN repositories r ON r.id = sd.repository_id WHERE detected_at >= NOW() - INTERVAL '30 days' GROUP BY 1, r.name ORDER BY 1","format":"time_series"}],"title":"Daily Detections by Repository","type":"timeseries"},{"datasource":{"type":"postgres","uid":"PostgreSQL"},"fieldConfig":{"defaults":{"color":{"mode":"palette-classic"},"custom":{"hideFrom":{"legend":false,"tooltip":false,"viz":false}},"mappings":[]},"overrides":[]},"gridPos":{"h":8,"w":12,"x":12,"y":8},"id":3,"options":{"legend":{"displayMode":"table","placement":"right","showLegend":true,"values":["value","percent"]},"pieType":"pie","reduceOptions":{"calcs":["sum"],"fields":"","values":true},"tooltip":{"mode":"single","sort":"none"}},"targets":[{"datasource":{"type":"postgres","uid":"PostgreSQL"},"sql":"SELECT secret_type, COUNT(*) as value FROM secret_detections sd WHERE detected_at >= NOW() - INTERVAL '30 days' GROUP BY secret_type ORDER BY value DESC","format":"table"}],"title":"Secret Types Distribution","type":"piechart"},{"datasource":{"type":"postgres","uid":"PostgreSQL"},"fieldConfig":{"defaults":{"color":{"mode":"thresholds"},"custom":{"align":"auto","cellOptions":{"type":"auto"}},"mappings":[],"thresholds":{"mode":"absolute","steps":[{"color":"green","value":null}]}},"overrides":[]},"gridPos":{"h":8,"w":24,"x":0,"y":16},"id":4,"options":{"footer":{"countRows":false,"fields":"","reducer":["sum"],"show":false},"showHeader":true},"targets":[{"datasource":{"type":"postgres","uid":"PostgreSQL"},"sql":"SELECT r.owner, r.name as repository, sd.secret_type, sd.branch_name, sd.author, sd.commit_hash, sd.detected_at, sd.is_blocked FROM secret_detections sd JOIN repositories r ON r.id = sd.repository_id WHERE detected_at >= NOW() - INTERVAL '7 days' ORDER BY detected_at DESC LIMIT 100","format":"table"}],"title":"Recent Detections (Last 7 Days)","type":"table"},{"datasource":{"type":"postgres","uid":"PostgreSQL"},"fieldConfig":{"defaults":{"color":{"mode":"continuous-GrYlRd"},"custom":{"fillOpacity":70,"lineWidth":0,"spanNulls":false},"mappings":[],"thresholds":{"mode":"absolute","steps":[{"color":"green","value":null},{"color":"red","value":80}]}},"overrides":[]},"gridPos":{"h":8,"w":24,"x":0,"y":24},"id":5,"options":{"calculate":false,"cellGap":1,"color":{"exponent":0.5,"fill":"dark-orange","mode":"scheme","reverse":false,"scale":"exponential","scheme":"RdYlGn","steps":64},"exemplars":{"color":"rgba(255,0,255,0.7)"},"filterValues":{"le":1e-9},"tooltip":{"show":true,"yHistogram":false},"yAxis":{"axisPlacement":"left","reverse":false}},"targets":[{"datasource":{"type":"postgres","uid":"PostgreSQL"},"sql":"SELECT date_trunc('day', detected_at) as time, r.name as metric, COUNT(*) as value FROM secret_detections sd JOIN repositories r ON r.id = sd.repository_id WHERE detected_at >= NOW() - INTERVAL '30 days' GROUP BY 1, 2 ORDER BY 1","format":"time_series"}],"title":"Detection Heatmap","type":"heatmap"}],"refresh":"5m","schemaVersion":38,"style":"dark","tags":["secrets","security","repositories"],"templating":{"list":[]},"time":{"from":"now-30d","to":"now"},"timepicker":{},"timezone":"","title":"Repository Secret Detection Metrics","uid":"repo-secrets-metrics","version":1,"weekStart":""}