{{- if not .Values.githubApp.githubSecret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets-detector.githubSecretName" . }}
  labels:
    {{- include "secrets-detector.githubAppLabels" . | nindent 4 }}
type: Opaque
data:
  webhook-secret: {{ .Values.githubApp.githubSecret.webhookSecret | b64enc }}
  app-id: {{ .Values.githubApp.githubSecret.appID | toString | b64enc }}
  installation-id: {{ .Values.githubApp.githubSecret.installationID | toString | b64enc }}
  # Note: In a real deployment, you would need to provide actual private keys
  github-pem: {{ "dummy-key-for-testing" | b64enc }}
  enterprise-pem: {{ "dummy-key-for-testing" | b64enc }}
---
{{- end }}

{{- if not .Values.postgres.credentials.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets-detector.postgresSecretName" . }}
  labels:
    {{- include "secrets-detector.postgresLabels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgres.credentials.username | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.postgres.credentials.password | b64enc }}
  POSTGRES_DB: {{ .Values.postgres.credentials.database | b64enc }}
  DB_USER: {{ .Values.postgres.credentials.username | b64enc }}
  DB_PASSWORD: {{ .Values.postgres.credentials.password | b64enc }}
  DB_NAME: {{ .Values.postgres.credentials.database | b64enc }}
---
{{- end }}

{{- if and .Values.grafana.enabled (not .Values.grafana.credentials.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets-detector.grafanaSecretName" . }}
  labels:
    {{- include "secrets-detector.grafanaLabels" . | nindent 4 }}
type: Opaque
data:
  GF_SECURITY_ADMIN_USER: {{ .Values.grafana.credentials.adminUser | b64enc }}
  GF_SECURITY_ADMIN_PASSWORD: {{ .Values.grafana.credentials.adminPassword | b64enc }}
{{- end }}